# Numpy Basics <hr style="border:2px solid #ff4fb0ff "><hr>

<b>Hazel Mae C. Jalandoni</b>
<br>Comp Eng Tech Student

# Imports and Packages

In [1]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array  Scalar

In [2]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [3]:
np.shape(my_array)

(3,)

# 2D Array  Vector

In [4]:
my_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.shape(my_array)

(3, 3)

# 3D Array - Matrix

In [6]:
my_array = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]])
my_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
np.shape(my_array)

(3, 3, 3)

# 4D Array - Tensor

In [8]:
my_array = np.array([[[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]],
                     
                     [[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]],
                     
                     [[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]]]
)
my_array

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [9]:
np.shape(my_array)

(3, 3, 3, 3)

# Measures of Central Tendency

In [10]:
# Jaguar vs Panther
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])

resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [11]:
np.shape(resistance)

(2, 11)

# Solving Mean

In [12]:
res_mean = np.nanmean(resistance, axis=1)
res_mean[0]

np.float64(9.399999999999999)

In [13]:
print(f'Jaguar Mean: {res_mean[0]:.2f} ohms')
print(f'Panther Mean: {res_mean[1]:.2f} ohms')

Jaguar Mean: 9.40 ohms
Panther Mean: 10.75 ohms


# Solving Median

In [14]:
res_median = np.nanmedian(resistance, axis=1)
res_median[0]

np.float64(9.8)

In [15]:
print(f'Jaguar Median: {res_median[0]:.2f} ohms')
print(f'Panther Median: {res_median[1]:.2f} ohms')

Jaguar Median: 9.80 ohms
Panther Median: 9.55 ohms


# Solving Mode

In [16]:
res_mode = stats.mode(resistance, axis=1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [17]:
jag_res = resistance[0]

print("Jaguar Mode(s):")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar Mode(s):
9.8 ohms
10.4 ohms


In [18]:
pan_res = resistance[1]

print("Panther Mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther Mode:
9.1 ohms


# Solving Range

In [19]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [20]:
print(f'Jaguar Range: {res_range[0]:.2f} ohms')
print(f'Panther Range: {res_range[1]:.2f} ohms')

Jaguar Range: 8.00 ohms
Panther Range: 10.90 ohms


# Solving Q1

In [21]:
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [22]:
print(f'Jaguar Q1: {res_Q1[0]:.2f} ohms')
print(f'Panther Q1: {res_Q1[1]:.2f} ohms')

Jaguar Q1: 9.40 ohms
Panther Q1: 9.12 ohms


# Solving Q3

In [23]:
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [24]:
print(f'Jaguar Q3: {res_Q3[0]:.2f} ohms')
print(f'Panther Q3: {res_Q3[1]:.2f} ohms')

Jaguar Q3: 10.45 ohms
Panther Q3: 10.62 ohms


# Solving IQR

In [25]:
print(f'Jaguar IQR: {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR: {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR: 1.05 ohms
Panther IQR: 1.50 ohms


# Solving Variance

In [26]:
res_var = np.nanvar(resistance, ddof=1, axis=1)
res_var

array([ 4.86      , 11.08277778])

In [27]:
print(f'Jaguar Variance: {res_var[0]:.2f} ohms')
print(f'Panther Variance: {res_var[1]:.2f} ohms')

Jaguar Variance: 4.86 ohms
Panther Variance: 11.08 ohms


# Solving Standard Deviation

In [28]:
res_std = np.nanstd(resistance, ddof=1, axis=1)
res_std

array([2.20454077, 3.32908062])

In [29]:
print(f'Jaguar Standard Deviation: {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation: {res_std[1]:.2f} ohms')

Jaguar Standard Deviation: 2.20 ohms
Panther Standard Deviation: 3.33 ohms
